# Generated by Django 4.0.1 on 2022-06-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbusto',
            fields=[
                ('nombreArbusto', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Arbusto')),
                ('precio', models.CharField(max_length=6, verbose_name='Precio Arbusto')),
                ('upload', models.ImageField(upload_to='A:\\Repo\\SOLEMNE-1\\TestDjango\\core\\static\\core\\img\\img_productos', verbose_name='Subir imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Flore',
            fields=[
                ('nombreFlore', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Flores')),
                ('precio', models.CharField(max_length=6, verbose_name='Precio Flores')),
                ('upload', models.ImageField(upload_to='A:\\Repo\\SOLEMNE-1\\TestDjango\\core\\static\\core\\img\\img_productos', verbose_name='Subir imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Macetero',
            fields=[
                ('nombreMacetero', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Arbusto')),
                ('precio', models.CharField(max_length=6, verbose_name='Precio Arbusto')),
                ('upload', models.ImageField(upload_to='A:\\Repo\\SOLEMNE-1\\TestDjango\\core\\static\\core\\img\\img_productos', verbose_name='Subir imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tierra_De_Hoja',
            fields=[
                ('nombreTierraDeHoja', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Arbusto')),
                ('precio', models.CharField(max_length=6, verbose_name='Precio Arbusto')),
                ('upload', models.ImageField(upload_to='A:\\Repo\\SOLEMNE-1\\TestDjango\\core\\static\\core\\img\\img_productos', verbose_name='Subir imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
