# Generated by Django 4.0.5 on 2022-06-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_remove_flore_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=6, verbose_name='Precio Producto'),
        ),
    ]
